In [17]:
import numpy as np
import tensorflow as tf

In [24]:
a=np.array([0.01,0.037,0.06,0.01])

In [25]:
a

array([0.01 , 0.037, 0.06 , 0.01 ])

In [26]:
a=1/a

In [27]:
a

array([100.        ,  27.02702703,  16.66666667, 100.        ])

In [28]:
a=(a/100)

In [29]:
a

array([1.        , 0.27027027, 0.16666667, 1.        ])