In [6]:
import numpy as np

In [2]:
arr=np.array([3,5])
arr2=np.array([0,1,2,3,4,5,6,7])

In [3]:
arr2[arr]

array([3, 5])

In [4]:
arr_index = np.random.randint(0, 10, (20, )) 

In [5]:
arr_index

array([0, 2, 3, 5, 5, 3, 6, 6, 8, 6, 3, 1, 9, 8, 4, 9, 2, 1, 2, 6])

In [1]:
#数据处理模块，以及依赖库导入
%run data_process.ipynb
import tensorflow as tf
import time
from net.base_cnn import Base_cnn
from net.triplet import triplet_net,triplet_loss
from tensorflow.keras import optimizers


from sklearn import datasets       #导入数据模块
from sklearn.model_selection import train_test_split     #导入切分训练集、测试集模块
from sklearn.neighbors import KNeighborsClassifier

from sklearn.manifold import TSNE
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
import numpy as np

In [2]:
#训练集降噪，测试集降噪，结果集降噪
reduce_noise()
reduce_noise_for_test()

train_data_reduce_noise
split_data\train\AD\AD_F_030807_001.wav


C:\Users\dell\AppData\Local\Temp\ipykernel_3596\3409515171.py:58: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  x = np.fromstring(str_data, dtype=np.short)
C:\Users\dell\AppData\Local\Temp\ipykernel_3596\3409515171.py:140: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  wf.writeframes(wave_data.tostring())


split_data\train\AD\AD_F_040006_001.wav
split_data\train\AD\AD_F_040006_002.wav
split_data\train\AD\AD_F_040108_001.wav
split_data\train\AD\AD_F_040108_002.wav
split_data\train\AD\AD_F_040108_003.wav
split_data\train\AD\AD_F_040108_004.wav
split_data\train\AD\AD_F_040108_005.wav
split_data\train\AD\AD_F_040108_006.wav
split_data\train\AD\AD_F_040108_007.wav
split_data\train\AD\AD_F_040108_008.wav
split_data\train\AD\AD_F_040108_009.wav
split_data\train\AD\AD_F_040108_010.wav
split_data\train\AD\AD_F_040108_011.wav
split_data\train\AD\AD_F_040108_012.wav
split_data\train\AD\AD_F_040108_013.wav
split_data\train\AD\AD_F_040108_014.wav
split_data\train\AD\AD_F_040108_015.wav
split_data\train\AD\AD_F_040108_016.wav
split_data\train\AD\AD_F_040108_017.wav
split_data\train\AD\AD_F_040108_018.wav
split_data\train\AD\AD_F_040108_019.wav
split_data\train\AD\AD_F_040108_020.wav
split_data\train\AD\AD_F_040108_021.wav
split_data\train\AD\AD_F_040108_022.wav
split_data\train\AD\AD_F_040108_023.wav


C:\Users\dell\AppData\Local\Temp\ipykernel_3596\3409515171.py:102: RuntimeWarning: divide by zero encountered in log10
  SNRseg = 10 * np.log10(np.linalg.norm(sig, 2) ** 2 / np.linalg.norm(noise_mu, 2) ** 2)


split_data\train\MCI\MCI_F_031912_002.wav
split_data\train\MCI\MCI_F_040316_001.wav
split_data\train\MCI\MCI_F_040377_001.wav
split_data\train\MCI\MCI_F_040381_001.wav
split_data\train\MCI\MCI_F_040381_002.wav
split_data\train\MCI\MCI_F_040381_003.wav
split_data\train\MCI\MCI_F_040381_004.wav
split_data\train\MCI\MCI_F_040386_001.wav
split_data\train\MCI\MCI_F_071913_001.wav
split_data\train\MCI\MCI_F_071913_002.wav
split_data\train\MCI\MCI_F_071913_003.wav
split_data\train\MCI\MCI_F_071913_004.wav
split_data\train\MCI\MCI_F_072313_001.wav
split_data\train\MCI\MCI_F_080312_001.wav
split_data\train\MCI\MCI_F_080312_002.wav
split_data\train\MCI\MCI_F_082417_001.wav
split_data\train\MCI\MCI_F_082417_002.wav
split_data\train\MCI\MCI_F_082417_003.wav
split_data\train\MCI\MCI_F_101024_001.wav
split_data\train\MCI\MCI_F_101026_001.wav
split_data\train\MCI\MCI_F_101026_002.wav
split_data\train\MCI\MCI_F_101206_001.wav
split_data\train\MCI\MCI_F_101206_002.wav
split_data\train\MCI\MCI_F_101206_

C:\Users\dell\AppData\Local\Temp\ipykernel_3596\3409515171.py:102: RuntimeWarning: invalid value encountered in double_scalars
  SNRseg = 10 * np.log10(np.linalg.norm(sig, 2) ** 2 / np.linalg.norm(noise_mu, 2) ** 2)
C:\Users\dell\AppData\Local\Temp\ipykernel_3596\3409515171.py:102: RuntimeWarning: divide by zero encountered in double_scalars
  SNRseg = 10 * np.log10(np.linalg.norm(sig, 2) ** 2 / np.linalg.norm(noise_mu, 2) ** 2)


split_data\test\MCI\0060.wav
split_data\test\MCI\0061.wav
split_data\test\MCI\0063.wav
split_data\test\MCI\0068.wav
split_data\test\MCI\0070.wav
split_data\test\MCI\0071.wav
split_data\test\MCI\0072.wav
split_data\test\MCI\0073.wav
split_data\test\MCI\0076.wav
split_data\test\MCI\0077.wav
split_data\test\MCI\0080.wav
split_data\test\MCI\0083.wav
split_data\test\MCI\0090.wav
split_data\test\MCI\0091.wav
split_data\test\MCI\0100.wav
split_data\test\MCI\0103.wav
split_data\test\MCI\0106.wav
split_data\test\MCI\0107.wav
split_data\test\MCI\0109.wav
split_data\test\MCI\0110.wav
split_data\test\MCI\0112.wav
split_data\test\MCI\0113.wav
split_data\test\MCI\0114.wav
split_data\test\MCI\0116.wav
test_data_reduce_noise
split_data\test_next\AD


PermissionError: [Errno 13] Permission denied: 'split_data\\test_next\\AD'

In [8]:
test=np.array([[[1,2,3],[1,2,3],[1,2,3]],[1,2,3],[1,2,3],[1,2,3],[[1,2,3],[1,2,3],[1,2,3]],[1,2,3],[1,2,3],[1,2,3]])

C:\Users\dell\AppData\Local\Temp\ipykernel_22924\4087746475.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  test=np.array([[[1,2,3],[1,2,3],[1,2,3]],[1,2,3],[1,2,3],[1,2,3],[[1,2,3],[1,2,3],[1,2,3]],[1,2,3],[1,2,3],[1,2,3]])


In [12]:
test=np.arange(500).reshape(10,50,1)

In [23]:
test.shape

(10, 50, 1)

In [24]:
test

array([[[  0],
        [  1],
        [  2],
        [  3],
        [  4],
        [  5],
        [  6],
        [  7],
        [  8],
        [  9],
        [ 10],
        [ 11],
        [ 12],
        [ 13],
        [ 14],
        [ 15],
        [ 16],
        [ 17],
        [ 18],
        [ 19],
        [ 20],
        [ 21],
        [ 22],
        [ 23],
        [ 24],
        [ 25],
        [ 26],
        [ 27],
        [ 28],
        [ 29],
        [ 30],
        [ 31],
        [ 32],
        [ 33],
        [ 34],
        [ 35],
        [ 36],
        [ 37],
        [ 38],
        [ 39],
        [ 40],
        [ 41],
        [ 42],
        [ 43],
        [ 44],
        [ 45],
        [ 46],
        [ 47],
        [ 48],
        [ 49]],

       [[ 50],
        [ 51],
        [ 52],
        [ 53],
        [ 54],
        [ 55],
        [ 56],
        [ 57],
        [ 58],
        [ 59],
        [ 60],
        [ 61],
        [ 62],
        [ 63],
        [ 64],
        [ 65],
        

In [29]:
test2=test[:,0:5]

In [30]:
test2.shape

(10, 5, 1)

In [5]:
import tensorflow as tf

In [6]:
aaa = tf.ones((3,3,3,3))
ccc = tf.constant([[[1,1,1,1,1,1],[2,2,2,2,2,2],[3,3,3,3,3,3]],[[1,1,1,1,1,1],[2,2,2,2,2,2],[3,3,3,3,3,3]]])

In [7]:
aaa.shape

TensorShape([3, 3, 3, 3])

In [8]:
aaa[:,0]

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [3]:
b=aaa.shape
print(b)

(2, 3, 6)


In [4]:
aaa[:1]

<tf.Tensor: shape=(1, 3, 6), dtype=int32, numpy=
array([[[1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3]]])>

In [4]:
b[0]

2

In [5]:
# aaa=tf.reshape(aaa,(b[0],1,b[1],b[2]))
# ccc=tf.reshape(ccc,(b[0],1,b[1],b[2]))

In [6]:
aaa=tf.expand_dims(aaa,[1])
ccc=tf.expand_dims(ccc,[1])

In [7]:
tf.concat([aaa, ccc],axis = 1)

<tf.Tensor: shape=(2, 2, 3, 6), dtype=int32, numpy=
array([[[[1, 1, 1, 1, 1, 1],
         [2, 2, 2, 2, 2, 2],
         [3, 3, 3, 3, 3, 3]],

        [[1, 1, 1, 1, 1, 1],
         [2, 2, 2, 2, 2, 2],
         [3, 3, 3, 3, 3, 3]]],


       [[[1, 1, 1, 1, 1, 1],
         [2, 2, 2, 2, 2, 2],
         [3, 3, 3, 3, 3, 3]],

        [[1, 1, 1, 1, 1, 1],
         [2, 2, 2, 2, 2, 2],
         [3, 3, 3, 3, 3, 3]]]])>

In [11]:
aaa[:,:,2].shape[0]

2

In [9]:
ccc

<tf.Tensor: shape=(2, 1, 3, 6), dtype=int32, numpy=
array([[[[1, 1, 1, 1, 1, 1],
         [2, 2, 2, 2, 2, 2],
         [3, 3, 3, 3, 3, 3]]],


       [[[1, 1, 1, 1, 1, 1],
         [2, 2, 2, 2, 2, 2],
         [3, 3, 3, 3, 3, 3]]]])>

In [10]:

c = tf.constant([])

In [4]:
c

<tf.Tensor: shape=(0,), dtype=float32, numpy=array([], dtype=float32)>

In [8]:
c=c.append(aaa)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'append'

In [12]:
def test(a):
    if a==1:
        c=2
    else:
        c=3
    return c

In [13]:
test(1)

2

In [1]:
import numpy as np

In [5]:
data=[[],[]]

In [6]:
data[0].append(1)
data[0].append(2)
data[0].append(3)
data[0].append(4)
data[0].append(5)

In [7]:
np.random.shuffle(data[0])

In [8]:
data[0]

[5, 3, 2, 4, 1]

In [9]:
import random

In [11]:
for i in range(30):
    print(random.randrange(1, 2))

1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
